/*
 * File: app/model/Solution.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('sql_executor.model.RunDetail', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'run_id'
        },
        {
            name: 'sql_text'
        },
        {
            name: 'start_time'
        },
         {
            name: 'end_time'
        },
        {
            name: 'result'
        },
        {
            name: 'status'
        },
        {
            name: 'run_by'
        }
    ]
});