/*
 * File: app/controller/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('main.controller.Navigation', {
    extend: 'Ext.app.Controller',

    models: [
        'Solution'
    ],
    stores: [
        'Navigation'
    ],
    views: [
        'MainPage'
    ],
    onFunctionSelect: function(dataview, record, item, index, e, eOpts) {
        if (record.raw.target != null) {

            var contentPanel = Ext.ComponentQuery.query("tabpanel")[0];

            if (record.raw.type == 'url') {
                var newPage = Ext.create('Ext.panel.Panel', {
                    title : record.raw.text,
                    closable : true,
                    autoScroll : true,
                    frame : false,
                    scripts : true,
                    html : " <iframe scrolling='auto' frameborder='0'  width='100%' height='100%' src='"
                    +CF_ROOT+ record.raw.target + "'> </iframe>"
                });
            }
           
             if (record.raw.type == 'extpage') {
                var newPage = Ext.create('main.view.MainPage');
            }
            contentPanel.add(newPage);
            contentPanel.show();
            contentPanel.setActiveTab(newPage);
        }
    },

    onLaunch: function() {
    	me.getStore('Navigation').load();
    },

    init: function(application) {
        this.control({
            "treepanel": {
            	itemclick: this.onFunctionSelect
            }
        });
    }

});
