/*
 * File: app/view/main_page.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('main.view.MainPage', {
    extend: 'Ext.container.Viewport',

    layout: {
        padding: '0 5 5 5',
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    region: 'north',
                    height: 40,
                    html: '<div class="logo">\r\n <span> Planing Toolbox </span>\r\n<div class="masthead">\r\n<span> User:      </span>\r\n <a href="/usersecurity/logout">logou</a>\r\n</div>\r\n</div>',
                    id: 'app-header'
                },
                {
                    xtype: 'panel',
                    setData: function(navigation) {
                        var hidList = new Array();
                        solutions=navigation;
                        for (var i = 0; i < solutions.length; i++) {

                            var treeMenu = Ext.create('Ext.tree.Panel', {
                                id : solutions[i].data.id,
                                title : solutions[i].data.text,
                                iconCls : solutions[i].data.icon,
                                border: false,
                                rootVisible : false,
                                collapsible : true,
                                margin: "3px",
                                root : {
                                    text : 'Root',
                                    children : solutions[i].data.children
                                }
                            });


                            /*
                            treeMenu.on('itemClick', function(tree, record, item, index, e,
                            eOpts) {
                            if (record.get('leaf')) {
                            //this.application.fireEvent('startFunction', record);
                        }

                    });

                    solutionPanel.on('expand', function(panel, eOpts) {
                        panel.doLayout();
                    });
                    // treeMenu.setRootNode(solutions[i].data.menuTree);
                    solutionPanel.items.add(treeMenu);

                    */

                    this.items.add(treeMenu);

                    if(!solutions[i].data.expanded)
                    {
                        hidList.push(treeMenu);
                    }
                }
                this.doLayout();

                for(var i=0;i<hidList.length;i++)
                {
                    hidList[i].collapse();
                }
                    },
                    region: 'west',
                    split: true,
                    id: 'NavigationPanel',
                    maxWidth: 400,
                    minWidth: 100,
                    width: 200,
                    animCollapse: true,
                    collapsible: true,
                    title: 'Navigation'
                },
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    split: true,
                    stateId: 'mainnav.west',
                    stateful: true,
                    id: 'ContentPanel',
                    header: false
                }
            ]
        });

        me.callParent(arguments);
    }

});