/*
 * File: app/view/main_page.js
 * 
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 * 
 * This file requires use of the Ext JS 4.2.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.2.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 * 
 * This file will be auto-generated each and everytime you save your project.
 * 
 * Do NOT hand edit this file.
 */

Ext
		.define(
				'main.view.MainPage',
				{
					extend : 'Ext.container.Viewport',

					controllers : [ 'Navigation' ],

					layout : {
						padding : '5 5 5 5',
						type : 'border'
					},

					initComponent : function() {
						var me = this;
						me.application.getController(me.controllers);

						Ext
								.applyIf(
										me,
										{
											items : [
													{
														xtype : 'treepanel',
														title : 'Navigation',
														collapsible : 'left',
														// border : false,
														// split : true,
														rootVisible : false,
														store : 'Navigation',
														margin : "2px",
														region : 'west',
														maxWidth : 400,
														minWidth : 100,
														width : 200,
														tools : [ {
															type : 'help',
															tooltip : 'Get Help',
															handler : function(
																	event,
																	toolEl,
																	panelHeader) {
																window
																		.open(
																				'/static/HelpPublish/index.html?execute.htm',
																				'popUp4',
																				'height=768,width=1024,scrollbars=yes,resizable=yes');
															}
														} ]
													},
													{
														xtype : 'tabpanel',
														region : 'center',
														margin : "2px",
														//split : true,
														stateId : 'mainnav.center',
														stateful : true,
														// id : 'ContentPanel',
														header : false
													} ]
										});

						me.callParent(arguments);
					}

				});