/*
 * File: app/view/main_page.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent
 * license. License of Sencha Architect does not include license for Ext JS
 * 4.2.x. For more details see http://www.sencha.com/license or contact
 * license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('free_query.view.ViewReport', {
	extend : 'Ext.container.Viewport',
	controllers:['ViewReport'],

	initComponent : function() {
		var me = this;
		me.application.getController(me.controllers);

		Ext.applyIf(me, {
			items : [{
				xtype : 'tabpanel',
				frame : false,
				activeTab: 0,
				id:'viewReportTabpanel',
				height : '100%',
				autoHeight : true,
				autoScroll : true,
				defaults : {
					height : 700
				},
				items : [{
					xtype : 'searchreport'
				}]
			}]
		});

		me.callParent(arguments);
	}
});
