/*
 * File: app/model/Solution.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('free_query.model.ReportProp', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'rpt_id'
        },
        {
            name: 'col_name'
        },
        {
            name: 'data_type'
        },
        {
            name: 'display_name'
        },
        {
            name: 'format'
        },
        {
            name: 'seq'
        },
        {
            name: 'is_filter'
        },
        {
            name: 'filter_type'
        },
         {
            name: 'req_filter'
        },
         {
            name: 'selection'
        },
        {
            name: 'width'
        }
    ]
});